[package]
authors = ["d0iasm"]
name = "ui_wasabi"
version = "0.1.0"
edition = "2021"

[dependencies]
tinybmp = "0.5.0"
embedded-graphics = "0.8.1"
saba_core = { path = "../../core" }
noli = { git = "https://github.com/hikalium/wasabi.git", version = "0.1.0" }
